apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  labels:
    app: blue-green-app
spec:
  type: ClusterIP
  selector:
    app: blue-green-app
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
